model_name: 'Segformer'
num_classes: 2

train:
  learning_rate: 0.00006 
  dropout_rate: 0.3
  batch_size: 16        
  num_epochs: 50
  weight_decay: 0.01
  loss_fn:
    name: "CrossEntropyLoss"
    params: {}  
  optimizer: 
    name: "AdamW"
    params: {}
  scaler: GradScaler
data:
  img_height: 512
  img_width: 512
  
two_stage_training:
  enable: true        
  epochs_stage1: 20   
  epochs_stage2: 40     
  lr_stage1: 0.0001      
  lr_stage2: 0.00001     

paths:
  accuracy_result_name: "Segformer_qualitative_results"
  latest_checkpoint_path: "segformer.pth"
  best_checkpoint_path: "best_segformer.pth"
  carbide_morphology_path: "Carbide_morphologies"
  
post_processing:
  tile_height: 512
  tile_width: 512
  lower_bound_color: [210, 210, 0]
  upper_bound_color: [255, 255, 80]
  nm_per_pixel_base_mag: 61.8
  min_precipitate_pixel_area: 30
  excluded_magnification: 2500
  figure_dpi: 600
  contour_area_min: 50
  contour_area_max: 10000000
  box_color_bgr: [106, 106, 255]
